stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
    - src/preprocess.py
    params:
    - preprocess.output
    outs:
    - DataBase/processed_data.csv
  train:
    cmd: python src/train.py
    deps:
    - DataBase/processed_data.csv
    - src/train.py
    params:
    - train.data
    - train.model
    - train.n_components
    - train.ramdom_state
    outs:
    - models/model.pkl
  evaluate:
    cmd: python src/evaluation.py
    deps:
    - DataBase/processed_data.csv
    - models/model.pkl
    - src/evaluation.py
